export const GET_MACHINES = 'GET_MACHINES';
export const UPDATE_MACHINE = 'UPDATE_MACHINE';
export const UPDATE_MACHINE_NAME = 'UPDATE_MACHINE_NAME';
export const UPDATE_MACHINES_LOCALLY = 'UPDATE_MACHINES_LOCALLY';
